index.html

<script src="shuffle.js"></script>
<script src="script.js"></script>
</body>
</html>

<!-- Script -->

---

index.html

<div class="radio-container">
<label for="value-50">50 Questions</label>
<input type="radio" name="questions" value="50" id="value-50">
<span class="best-score">
<span>Best Score</span>
<span class="best-score-value"></span>
</span>
</div>

<!-- 50 Questions Radio Input -->

---

index.html

<div class="radio-container">
<label for="value-99">99 Questions</label>
<input type="radio" name="questions" value="99" id="value-99">
<span class="best-score">
<span>Best Score</span>
<span class="best-score-value"></span>
</span>
</div>
</div>
<div class="selection-footer">
<button class="start" type="submit">Start Round</button>
</div>
</form>
</div>

<!-- 99 Questions Radio Input -->

---

index.html

<div class="card" id="countdown-page" hidden>
<h1 class="countdown">3</h1>
</div>
<div class="card" id="game-page" hidden>
<div class="item-container"></div>
<div class="item-footer">
<button class="wrong" onclick="select(false)">Wrong</button>
<button class="right" onclick="select(true)">Right</button>
</div>
</div>

 <!-- Countdown Page -->

---

index.html

<div class="card" id="score-page" hidden>
<div class="score-container">
<h1 class="title">Your Time</h1>
<h1 class="final-time"></h1>
<h1 class="base-time"></h1>
<h1 class="penalty-time"></h1>
</div>
<div class="score-footer">
<button class="play-again" onclick="playAgain()" hidden>Play Again</button>
</div>
</div>

 <!-- Score Page -->

---

style.css

border: 1px solid black;
box-shadow: 0 10px 20px -5px rgba(0, 0, 0, 0.5);
width: 530px;
height: 750px;
background: rgba(255, 255, 255, 0.5);
user-select: none;
margin-top: 100px;
}

.game-container {

---

style.css

top: 65px;
}
.radio-container {
width: 90%;
height: 75px;
margin: 25px;
cursor: pointer;
border: 2px solid black;
border-radius: 5px;
}

.selection-container {

---

style.css

top: -100px;
left: 330px;
display: flex;
flex-direction: column;
justify-content: center;
text-align: center;
font-size: 18px;
max-width: fit-content;
}
.best-score span {
margin: 0;
}
.best-score span:last-child {
font-size: 24px;
}

.best-score {

---

style.css

top: 134px;
}
/* Game Page -------------------------- */
.height-240 {
height: 240px;
width: 100%;
}
.height-500 {
height: 500px;
width: 100%;
}

.selection-footer {

---

style.css

opacity: 0.5;
}
.selected-item {
background: var(--select-color);
position: fixed;
top: 443px;
z-index: -1;
width: 529px;
height: 80px;
}

.finished > h1 {

---

style.css

.selection-footer {
width: 100%;
height: 90px;
background: rgba(0, 0, 0, 1);
display: flex;
justify-content: center;
align-items: center;
}
.item-footer {
top: 1px;
}

.item-footer,

---

style.css

.countdown {
margin-top: 45%;
font-size: 100px;
text-align: center;
user-select: none;
cursor: pointer;
}

/* Countdown Page ---------------------- */

---

style.css

.score-container {
height: 600px;
display: flex;
flex-direction: column;
justify-content: center;
align-items: center;
}

/* Score Page ------------------------- */

---

style.css

width: 100%;
height: 90px;
display: flex;
justify-content: center;
top: -30px;
}

.score-footer {

---

style.css

margin-top: 100px;
margin-bottom: 0;
}
.penalty-time {
color: var(--danger);
}

.base-time {

---

style.css

@media screen and (max-width: 1800px) {
.game-container {
margin-top: 35px;
}
.selected-item {
top: 380px;
}
}

/* Media Query: Laptop */

---

style.css

@media screen and (max-width: 500px) {
.game-container {
width: 100%;
margin-top: 0;
border: none;
}
.selected-item {
top: 345px;
}
.header {
font-size: 1.2rem;
}
.countdown {
margin-top: 60%;
}
.selection-container {
top: 100px;
}
.radio-container {
width: 93%;
margin: 15px;
}
label {
font-size: 1.7rem;
}
.final-time {
font-size: 50px;
}
.best-score {
font-size: 1rem;
left: 245px;
}
.selection-footer {
top: 183px;
}
}

/* Media Query: Large Smartphone (Vertical) */

---

style.css

@media screen and (max-width: 376px) {
.best-score {
left: 232px;
}
}

/* Media Query: iPhone */

---

script.js

const startForm = document.getElementById('start-form'); const radioContainers = document.querySelectorAll('.radio-container'); const radioInputs = document.querySelectorAll('input'); const bestScores = document.querySelectorAll('.best-score-value');

// Splash Page

---

script.js

const countdown = document.querySelector('.countdown'); // Game Page
const itemContainer = document.querySelector('.item-container'); // Score Page
const finalTimeEl = document.querySelector('.final-time'); const baseTimeEl = document.querySelector('.base-time'); const penaltyTimeEl = document.querySelector('.penalty-time'); const playAgainBtn = document.querySelector('.play-again');

// Countdown Page

---

script.js

let questionAmount = 0;
let equationsArray = [];
let playerGuessArray = [];
let bestScoreArray = [];

// Equations

---

script.js

let firstNumber = 0;
let secondNumber = 0;
let equationObject = {};
const wrongFormat = [];

// Game Page

---

script.js

function bestScoresToDOM() {
bestScores.forEach((bestScore, index) => {
const bestScoreEl = bestScore;
bestScoreEl.textContent = `${bestScoreArray[index].bestScore}s`;
});
}

// Refresh Splash Page Best Scores

---

script.js

function getSavedBestScores() {
if (localStorage.getItem('bestScores')) {
bestScoreArray = JSON.parse(localStorage.bestScores);
} else {
bestScoreArray = [
{ questions: 10, bestScore: finalTimeDisplay },
{ questions: 25, bestScore: finalTimeDisplay },
{ questions: 50, bestScore: finalTimeDisplay },
{ questions: 99, bestScore: finalTimeDisplay },
];
localStorage.setItem('bestScores', JSON.stringify(bestScoreArray));
}
bestScoresToDOM();
}

// Check Local Storage for Best Scores, Set bestScoreArray

---

script.js

function updateBestScore() {
bestScoreArray.forEach((score, index) => {
// Select correct Best Score to update
if (questionAmount == score.questions) {
// Return Best Score as number with one decimal
const savedBestScore = Number(bestScoreArray[index].bestScore);
// Update if the new final score is less or replacing zero
if (savedBestScore === 0 || savedBestScore < finalTime) {
bestScoreArray[index].bestScore = finalTimeDisplay;
}
}
});
// Update Splash Page
bestScoresToDOM();
// Save to Local Storage
localStorage.setItem('bestScores', JSON.stringify(bestScoreArray));
}

// Update Best Score Array

---

script.js

function playAgain() {
gamePage.addEventListener('click', startTimer);
scorePage.hidden = true;
splashPage.hidden = false;
equationsArray = [];
playerGuessArray = [];
valueY = 0;
playAgainBtn.hidden = true;
}

// Reset Game

---

script.js

function showScorePage() {
// Show Play Again button after 1 second delay
setTimeout(() => {
playAgainBtn.hidden = false;
}, 1000);
gamePage.hidden = true;
scorePage.hidden = false;
}

// Show Score Page

---

script.js

function checkTime() {
console.log(timePlayed);
if (playerGuessArray.length == questionAmount) {
clearInterval(timer);
// Check for wrong guess, add penaltyTime
equationsArray.forEach((equation, index) => {
if (equation.evaluated === playerGuessArray[index]) {
// Correct Guess, No Penalty
} else {
// Incorrect Guess, Add Penalty
penaltyTime += 0.5;
}
});
finalTime = timePlayed + penaltyTime;
console.log('time:', timePlayed, 'penalty:', penaltyTime, 'final:', finalTime);
scoresToDOM();
}
}

// Stop Timer, Process Results, go to Score Page

---

script.js

function addTime() {
timePlayed += 0.1;
checkTime();
}

// Add a tenth of a second to timePlayed

---

script.js

function startTimer() {
// Reset times
timePlayed = 0;
penaltyTime = 0;
finalTime = 0;
timer = setInterval(addTime, 100);
gamePage.removeEventListener('click', startTimer);
}

// Start timer when game page is clicked

---

script.js

function select(guessedTrue) {
// Scroll 80 more pixels
valueY += 80;
itemContainer.scroll(0, valueY);
// Add player guess to array
return guessedTrue ? playerGuessArray.push('true') : playerGuessArray.push('false');
}

// Scroll, Store user selection in playerGuessArray

---

script.js

function showGamePage() {
gamePage.hidden = false;
countdownPage.hidden = true;
}
// Get Random Number up to a certain amount
function getRandomInt(max) {
return Math.floor(Math.random() * Math.floor(max));
}

// Displays Game Page

---

script.js

function createEquations() {
// Randomly choose how many correct equations there should be
const correctEquations = getRandomInt(questionAmount);
console.log('correct equations:', correctEquations);
// Set amount of wrong equations
const wrongEquations = questionAmount - correctEquations;
console.log('wrong equations:', wrongEquations);
// Loop through for each correct equation, multiply random numbers up to 9, push to array
for (let i = 0; i < correctEquations; i++) {
firstNumber = getRandomInt(9);
secondNumber = getRandomInt(9);
const equationValue = firstNumber * secondNumber;
const equation = `${firstNumber} x ${secondNumber} = ${equationValue}`;
equationObject = { value: equation, evaluated: 'true' };
equationsArray.push(equationObject);
}
// Loop through for each wrong equation, …

// Create Correct/Incorrect Random Equations

---

script.js

function equationsToDOM() {
equationsArray.forEach((equation) => {
// Item
const item = document.createElement('div');
item.classList.add('item');
// Equation Text
const equationText = document.createElement('h1');
equationText.textContent = equation.value;
// Append
item.appendChild(equationText);
itemContainer.appendChild(item);
});
}

// Add Equations to DOM

---

script.js

function populateGamePage() {
// Reset DOM, Set Blank Space Above
itemContainer.textContent = '';
// Spacer
const topSpacer = document.createElement('div');
topSpacer.classList.add('height-240');
// Selected Item
const selectedItem = document.createElement('div');
selectedItem.classList.add('selected-item');
// Append
itemContainer.append(topSpacer, selectedItem);
// Create Equations, Build Elements in DOM
createEquations();
equationsToDOM();
// Set Blank Space Below
const bottomSpacer = document.createElement('div');
bottomSpacer.classList.add('height-500');
itemContainer.appendChild(bottomSpacer);
}

// Dynamically adding correct/incorrect equations

---

script.js

function countdownStart() {
let count=3
countdown.textContent=count
const timeCountDown=setInterval(()=>{
count--
if(count===0){
countdown.textContent="go"
}else if(count===-1){
showGamePage()
clearInterval(timeCountDown)
}else{
countdown.textContent=count
}
},1000)
// countdown.textContent = '3';
// setTimeout(() => {
//   countdown.textContent = '2';
// }, 1000);
// setTimeout(() => {
//   countdown.textContent = '1';
// }, 2000);
// setTimeout(() => {
//   countdown.textContent = 'GO!';
// }, 3000);
}

// Displays 3, 2, 1, GO!

---

script.js

function showCountdown() {
countdownPage.hidden = false;
splashPage.hidden = true;
countdownStart();
populateGamePage();
// setTimeout(showGamePage, 4000);
}

// Navigate from Splash Page to CountdownPage to Game Page

---

script.js

function getRadioValue() {
let radioValue;
radioInputs.forEach((radioInput) => {
if (radioInput.checked) {
radioValue = radioInput.value;
}
});
return radioValue;
}

// Get the value from selected radio button

---

script.js

function selectQuestionAmount(e) {
e.preventDefault();
questionAmount = getRadioValue();
console.log('question amount:', questionAmount);
if (questionAmount) {
showCountdown();
}
}

// Form that decides amount of Questions
